### ISSUE TITLE
Doc issue (Mac Fortran support)

### ISSUE THREAD

**Issue by ghutchis** [qmlcode/qml#25]
I was looking through the documentation to try it out. :-)

"Clang Fortran compiler" was mentioned here: http://www.qmlcode.org/installation.html#note-on-apple-mac-support

I think you mean that the "GCC Fortran compiler, gfortran" through homebrew does not include OpenMP support.

AFAIK, there is no Clang Fortran compiler.

You *can* get a gfortran from here, which I think includes the OpenMP support: http://hpc.sourceforge.net

**Comment by andersx** [comment]
Thanks, Geoff! Yeah, there seems to be some confusion here. I have some minor updates coming next week, I'll make sure to update the text.

I am not sure how I should go about updating setup.py, since the default  Fortran compiler on mac does not support OpenMP, so enabling this would break "pip install qml" for most mac users.

I am also working on adding build/testing on osx to Travis ci, although it has been a bit of a tedious task.

**Comment by andersx** [comment]
Updated installation instructions.
